name: GigaChad Ateeb's originally written CI

on:
  push:
    branches: [ main ]

permissions:
  contents: write

concurrency:
  group: deploy-${{ github.ref_name }}
  cancel-in-progress: true

jobs:

  deploy-to-vercel:
    needs: ci
    runs-on: ubuntu-latest
    env:
      # VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      # VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      # PROD_FLAG: ${{ github.ref_name == 'main' && '--prod' || '' }}
      # ENV_TARGET: ${{ github.ref_name == 'main' && 'production' || 'preview' }}
      # VERCEL_DEPLOY_HOOK is THE PREVIEW HOOK!
      VERCEL_DEPLOY_HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK }}

    steps:
      - name: Trigger Vercel
        run: |
          curl -X POST "${VERCEL_DEPLOY_HOOK}"
